// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 抓取课表原始 JSON 字符串。
///
/// 参数使用默认值：学期 241，bizTypeId 2，超时 30 秒。
/// 返回的 JSON 结构与教务系统 get-data 接口一致，供 Flutter 侧解析。
Future<String> fetchTimetableJsonFrb({
  required String ssoUsername,
  required String ssoPassword,
  required String jwxtUsername,
  required String jwxtPassword,
  required PlatformInt64 semesterId,
  required PlatformInt64 bizTypeId,
  required BigInt timeoutSec,
}) => RustLib.instance.api.crateApiFetchTimetableJsonFrb(
  ssoUsername: ssoUsername,
  ssoPassword: ssoPassword,
  jwxtUsername: jwxtUsername,
  jwxtPassword: jwxtPassword,
  semesterId: semesterId,
  bizTypeId: bizTypeId,
  timeoutSec: timeoutSec,
);

/// 使用默认参数快速获取课表 JSON（学期 241，超时 30 秒）
Future<String> fetchTimetableJsonSimpleFrb({
  required String ssoUsername,
  required String ssoPassword,
  required String jwxtUsername,
  required String jwxtPassword,
}) => RustLib.instance.api.crateApiFetchTimetableJsonSimpleFrb(
  ssoUsername: ssoUsername,
  ssoPassword: ssoPassword,
  jwxtUsername: jwxtUsername,
  jwxtPassword: jwxtPassword,
);

/// 第一阶段：初始化 SSO 登录并检查是否需要验证码。
///
/// - 返回 `None`：无需验证码，会话已存储，可直接调用 `fetch_timetable_json_with_captcha_frb`（captcha 传空）。
/// - 返回 `Some(bytes)`：需要验证码，bytes 为验证码图片数据（JPEG/PNG），展示给用户后传回。
Future<Uint8List?> checkSsoCaptchaFrb({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiCheckSsoCaptchaFrb(
  username: username,
  password: password,
);

/// 第二阶段：使用第一阶段存储的会话完成 SSO 登录并抓取课表。
///
/// `captcha`：验证码文本，无需验证码时传空字符串。
/// 需先调用 `check_sso_captcha_frb` 初始化会话。
Future<String> fetchTimetableJsonWithCaptchaFrb({
  required String jwxtUsername,
  required String jwxtPassword,
  required String captcha,
}) => RustLib.instance.api.crateApiFetchTimetableJsonWithCaptchaFrb(
  jwxtUsername: jwxtUsername,
  jwxtPassword: jwxtPassword,
  captcha: captcha,
);

/// 使用默认参数快速获取成绩 JSON（学期 221，超时 30 秒）
Future<String> fetchGradesJsonSimpleFrb({
  required String ssoUsername,
  required String ssoPassword,
  required String jwxtUsername,
  required String jwxtPassword,
}) => RustLib.instance.api.crateApiFetchGradesJsonSimpleFrb(
  ssoUsername: ssoUsername,
  ssoPassword: ssoPassword,
  jwxtUsername: jwxtUsername,
  jwxtPassword: jwxtPassword,
);

/// 成绩查询第一阶段：初始化 SSO 登录并检查是否需要验证码。
/// 与课表查询共享同一个会话机制。
///
/// - 返回 `None`：无需验证码，可直接调用 `fetch_grades_with_captcha_frb`（captcha 传空）。
/// - 返回 `Some(bytes)`：需要验证码，bytes 为验证码图片数据。
Future<Uint8List?> checkSsoCaptchaForGradesFrb({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiCheckSsoCaptchaForGradesFrb(
  username: username,
  password: password,
);

/// 成绩查询第二阶段：使用第一阶段存储的会话完成登录并获取成绩。
///
/// `captcha`：验证码文本，无需验证码时传空字符串。
/// 需先调用 `check_sso_captcha_for_grades_frb` 初始化会话。
Future<String> fetchGradesJsonFrb({
  required String jwxtUsername,
  required String jwxtPassword,
  required String captcha,
  required PlatformInt64 semesterId,
}) => RustLib.instance.api.crateApiFetchGradesJsonFrb(
  jwxtUsername: jwxtUsername,
  jwxtPassword: jwxtPassword,
  captcha: captcha,
  semesterId: semesterId,
);

/// 获取解析后的成绩数据（支持两阶段验证码）
Future<String> fetchGradesParsedFrb({
  required String jwxtUsername,
  required String jwxtPassword,
  required String captcha,
  required Int64List semesterIds,
}) => RustLib.instance.api.crateApiFetchGradesParsedFrb(
  jwxtUsername: jwxtUsername,
  jwxtPassword: jwxtPassword,
  captcha: captcha,
  semesterIds: semesterIds,
);
