// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1109291036;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cwnu_api',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List?> crateApiCheckSsoCaptchaForGradesFrb({
    required String username,
    required String password,
  });

  Future<Uint8List?> crateApiCheckSsoCaptchaFrb({
    required String username,
    required String password,
  });

  Future<String> crateApiFetchGradesJsonFrb({
    required String jwxtUsername,
    required String jwxtPassword,
    required String captcha,
    required PlatformInt64 semesterId,
  });

  Future<String> crateApiFetchGradesJsonSimpleFrb({
    required String ssoUsername,
    required String ssoPassword,
    required String jwxtUsername,
    required String jwxtPassword,
  });

  Future<String> crateApiFetchGradesParsedFrb({
    required String jwxtUsername,
    required String jwxtPassword,
    required String captcha,
    required Int64List semesterIds,
  });

  Future<String> crateApiFetchTimetableJsonFrb({
    required String ssoUsername,
    required String ssoPassword,
    required String jwxtUsername,
    required String jwxtPassword,
    required PlatformInt64 semesterId,
    required PlatformInt64 bizTypeId,
    required BigInt timeoutSec,
  });

  Future<String> crateApiFetchTimetableJsonSimpleFrb({
    required String ssoUsername,
    required String ssoPassword,
    required String jwxtUsername,
    required String jwxtPassword,
  });

  Future<String> crateApiFetchTimetableJsonWithCaptchaFrb({
    required String jwxtUsername,
    required String jwxtPassword,
    required String captcha,
  });

  Future<void> crateApiInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List?> crateApiCheckSsoCaptchaForGradesFrb({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCheckSsoCaptchaForGradesFrbConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckSsoCaptchaForGradesFrbConstMeta =>
      const TaskConstMeta(
        debugName: "check_sso_captcha_for_grades_frb",
        argNames: ["username", "password"],
      );

  @override
  Future<Uint8List?> crateApiCheckSsoCaptchaFrb({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCheckSsoCaptchaFrbConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckSsoCaptchaFrbConstMeta => const TaskConstMeta(
    debugName: "check_sso_captcha_frb",
    argNames: ["username", "password"],
  );

  @override
  Future<String> crateApiFetchGradesJsonFrb({
    required String jwxtUsername,
    required String jwxtPassword,
    required String captcha,
    required PlatformInt64 semesterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jwxtUsername, serializer);
          sse_encode_String(jwxtPassword, serializer);
          sse_encode_String(captcha, serializer);
          sse_encode_i_64(semesterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchGradesJsonFrbConstMeta,
        argValues: [jwxtUsername, jwxtPassword, captcha, semesterId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchGradesJsonFrbConstMeta => const TaskConstMeta(
    debugName: "fetch_grades_json_frb",
    argNames: ["jwxtUsername", "jwxtPassword", "captcha", "semesterId"],
  );

  @override
  Future<String> crateApiFetchGradesJsonSimpleFrb({
    required String ssoUsername,
    required String ssoPassword,
    required String jwxtUsername,
    required String jwxtPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ssoUsername, serializer);
          sse_encode_String(ssoPassword, serializer);
          sse_encode_String(jwxtUsername, serializer);
          sse_encode_String(jwxtPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchGradesJsonSimpleFrbConstMeta,
        argValues: [ssoUsername, ssoPassword, jwxtUsername, jwxtPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchGradesJsonSimpleFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_grades_json_simple_frb",
        argNames: [
          "ssoUsername",
          "ssoPassword",
          "jwxtUsername",
          "jwxtPassword",
        ],
      );

  @override
  Future<String> crateApiFetchGradesParsedFrb({
    required String jwxtUsername,
    required String jwxtPassword,
    required String captcha,
    required Int64List semesterIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jwxtUsername, serializer);
          sse_encode_String(jwxtPassword, serializer);
          sse_encode_String(captcha, serializer);
          sse_encode_list_prim_i_64_strict(semesterIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchGradesParsedFrbConstMeta,
        argValues: [jwxtUsername, jwxtPassword, captcha, semesterIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchGradesParsedFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_grades_parsed_frb",
        argNames: ["jwxtUsername", "jwxtPassword", "captcha", "semesterIds"],
      );

  @override
  Future<String> crateApiFetchTimetableJsonFrb({
    required String ssoUsername,
    required String ssoPassword,
    required String jwxtUsername,
    required String jwxtPassword,
    required PlatformInt64 semesterId,
    required PlatformInt64 bizTypeId,
    required BigInt timeoutSec,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ssoUsername, serializer);
          sse_encode_String(ssoPassword, serializer);
          sse_encode_String(jwxtUsername, serializer);
          sse_encode_String(jwxtPassword, serializer);
          sse_encode_i_64(semesterId, serializer);
          sse_encode_i_64(bizTypeId, serializer);
          sse_encode_u_64(timeoutSec, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchTimetableJsonFrbConstMeta,
        argValues: [
          ssoUsername,
          ssoPassword,
          jwxtUsername,
          jwxtPassword,
          semesterId,
          bizTypeId,
          timeoutSec,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchTimetableJsonFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_timetable_json_frb",
        argNames: [
          "ssoUsername",
          "ssoPassword",
          "jwxtUsername",
          "jwxtPassword",
          "semesterId",
          "bizTypeId",
          "timeoutSec",
        ],
      );

  @override
  Future<String> crateApiFetchTimetableJsonSimpleFrb({
    required String ssoUsername,
    required String ssoPassword,
    required String jwxtUsername,
    required String jwxtPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ssoUsername, serializer);
          sse_encode_String(ssoPassword, serializer);
          sse_encode_String(jwxtUsername, serializer);
          sse_encode_String(jwxtPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchTimetableJsonSimpleFrbConstMeta,
        argValues: [ssoUsername, ssoPassword, jwxtUsername, jwxtPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchTimetableJsonSimpleFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_timetable_json_simple_frb",
        argNames: [
          "ssoUsername",
          "ssoPassword",
          "jwxtUsername",
          "jwxtPassword",
        ],
      );

  @override
  Future<String> crateApiFetchTimetableJsonWithCaptchaFrb({
    required String jwxtUsername,
    required String jwxtPassword,
    required String captcha,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jwxtUsername, serializer);
          sse_encode_String(jwxtPassword, serializer);
          sse_encode_String(captcha, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchTimetableJsonWithCaptchaFrbConstMeta,
        argValues: [jwxtUsername, jwxtPassword, captcha],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchTimetableJsonWithCaptchaFrbConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_timetable_json_with_captcha_frb",
        argNames: ["jwxtUsername", "jwxtPassword", "captcha"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
